name: SkinDownloader
main: me.ansandr.skindownloader.SkinDownloader
version: 1.0.0
author: Ansandr
api-version: 1.13
description: Get a png file of player skin
softdepend: [SkinsRestorer]
loadbefore: [SkinsRestorer]

commands:
  getskin:
  getcape: